#!/bin/bash
# lib/trusttunnel.sh — canonical TrustTunnel client-bundle writer.
#
# Single source of truth for the per-user TrustTunnel client files, shared by the
# host `moav user add` path (singbox-user-add.sh) and the container bundle
# generator (generate-user.sh). Both previously carried their own copy and had
# drifted: the host hardcoded `has_ipv6 = false`, so a user provisioned with
# `moav user add` on an IPv6-capable server got a config that never used IPv6.
#
# Server-side credentials (configs/trusttunnel/credentials.toml) are NOT written
# here — the host appends to them in singbox-user-add.sh and the container gets
# them from the bootstrap template.

# trusttunnel_write_client_bundle <output_dir> <username> <password>
# Writes trusttunnel.toml (full CLI-client config) + trusttunnel.json (the same
# connection details for programmatic use). Reads DOMAIN / SERVER_IP /
# SERVER_IPV6 from the environment; the setup guide lives in README.html.
trusttunnel_write_client_bundle() {
    local out="$1" user="$2" password="$3"

    # Proper boolean. The previous container-side expression
    # `${SERVER_IPV6:+true}${SERVER_IPV6:-false}` reads like a ternary but isn't:
    # when SERVER_IPV6 is set, `:+` yields "true" AND `:-` yields the address, so
    # it emitted `has_ipv6 = true2001:db8::1` — invalid TOML the client can't
    # parse. It only looked fine on hosts without IPv6 (where it renders "false").
    local has_ipv6=false
    [[ -n "${SERVER_IPV6:-}" ]] && has_ipv6=true

    cat > "$out/trusttunnel.toml" <<EOF
# TrustTunnel Client Configuration for $user
# Generated by MoaV

loglevel = "info"
vpn_mode = "general"
killswitch_enabled = false
killswitch_allow_ports = []
post_quantum_group_enabled = true
exclusions = []

[endpoint]
hostname = "${DOMAIN}"
dns_upstreams = ["tls://1.1.1.1"]
addresses = ["${SERVER_IP}:4443"]
has_ipv6 = ${has_ipv6}
username = "${user}"
password = "${password}"
client_random = ""
skip_verification = false
certificate = ""
upstream_protocol = "http2"
upstream_fallback_protocol = "http3"
anti_dpi = false

[listener.tun]
bound_if = ""
included_routes = ["0.0.0.0/0", "2000::/3"]
excluded_routes = ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
mtu_size = 1280
EOF

    cat > "$out/trusttunnel.json" <<EOF
{
  "ip_address": "${SERVER_IP}:4443",
  "domain": "${DOMAIN}",
  "username": "${user}",
  "password": "${password}",
  "dns_servers": ["tls://1.1.1.1"]
}
EOF
}
